In [1]:
import numpy as np

scores = np.array([86, 64, 79])
print(type(scores))
scores + 3

<class 'numpy.ndarray'>


array([89, 67, 82])

In [2]:
print(scores.sum())
print(scores.mean())
print(scores.std())
print(scores.min())
print(scores.max())
np.median(scores)

229
76.33333333333333
9.177266598624136
64
86


np.float64(79.0)

In [4]:
#numpy的二維運算
students = np.array([
    [64, 85, 76], 
    [94, 67, 84], 
    [75, 61, 69]
    ])
students

array([[64, 85, 76],
       [94, 67, 84],
       [75, 61, 69]])

In [ ]:
#常用的查詢屬性
students.ndim, students.size, students.shape, students.dtype

(2, 9, (3, 3), dtype('int64'))

In [9]:
students[0,0]

np.int64(64)

In [10]:
#第一位學生的分數
students[0,:]

array([64, 85, 76])

In [11]:
#前2個學生的分數
students[0:2,:]

array([[64, 85, 76],
       [94, 67, 84]])

In [12]:
#最後2個學生的分數
students[-2:]

array([[94, 67, 84],
       [75, 61, 69]])

In [13]:
#第一列展示
students[:,0]

array([64, 94, 75])

In [14]:
students[:,:2]

array([[64, 85],
       [94, 67],
       [75, 61]])

In [15]:
students = np.array([
    [64, 85, 76], 
    [94, 67, 84], 
    [75, 61, 69]
    ])
students

array([[64, 85, 76],
       [94, 67, 84],
       [75, 61, 69]])

In [16]:
students[0,0] = 100
students

array([[100,  85,  76],
       [ 94,  67,  84],
       [ 75,  61,  69]])

In [32]:
students[0,0] -= 10
students

array([[-140,  -25,  -34],
       [ -16,  -43,  -26],
       [ -35,  -49,  -41]])